version: '3.7'

services:
  board:
    build: ./project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project/:/usr/src/project/
    ports:
      - 8000:8000
    env_file:
      - ./project/.env.dev
    depends_on:
      - board-db
      - redis
  board-db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=board
      - POSTGRES_PASSWORD=board
      - POSTGRES_DB=board_dev
  redis:
    image: redis:alpine
  celery:
    build: ./project
    command: celery -A core worker -l info
    volumes:
      - ./project/:/usr/src/project/
    env_file:
      - ./project/.env.dev
    depends_on:
      - redis
  celery-beat:
    build: ./project
    command: celery -A core beat -l info
    volumes:
      - ./project/:/usr/src/project/
    env_file:
      - ./project/.env.dev
    depends_on:
      - redis
volumes:
  postgres_data: