version: '3.7'

services:
  board:
    build: ./project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./project/:/usr/src/project/
    ports:
      - 8000:8000
    env_file:
      - ./project/.env.dev
    depends_on:
      - board-db
  board-db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=board
      - POSTGRES_PASSWORD=board
      - POSTGRES_DB=board_dev

volumes:
  postgres_data: