# Generated by Django 3.0.7 on 2020-06-20 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostUpvote',
            new_name='Upvote',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='upvotes',
        ),
        migrations.DeleteModel(
            name='CommentUpvote',
        ),
    ]
